"""Align SERIAL sequence for monitors.id

Revision ID: 801291b0a33a
Revises: 65218e444685
Create Date: 2026-02-08 14:14:26.416961

This migration exists to normalize Postgres sequence handling
for the monitors.id primary key. No schema changes are applied.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801291b0a33a'
down_revision: Union[str, Sequence[str], None] = '65218e444685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
